"""
Generate results/RESULTS.md from the artifacts under results/.

The report is built from the CSV/JSON files the stages write, never from
in-memory state, so `python main.py --stages report` regenerates it faithfully
after any subset of stages has run. Interpretation and caveats live in
docs/RESULTS.md and docs/METHODS.md, which are written by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from . import config as cfg
from . import evaluation as ev


def _fmt(x, nd: int = 3) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "–"
    if isinstance(x, (bool, np.bool_)):
        return str(bool(x))
    if isinstance(x, (int, np.integer)):
        return str(int(x))
    if isinstance(x, (float, np.floating)):
        return f"{float(x):.{nd}f}"
    return str(x)


def _table(df: pd.DataFrame, cols: list[str], nd: int = 3) -> str:
    cols = [c for c in cols if c in df.columns]
    head = "| " + " | ".join(cols) + " |\n|" + "|".join(["---"] * len(cols)) + "|\n"
    rows = ["| " + " | ".join(_fmt(r[c], nd) for c in cols) + " |" for _, r in df.iterrows()]
    return head + "\n".join(rows) + "\n"


def _csv(path: Path, **kw) -> pd.DataFrame | None:
    return pd.read_csv(path, **kw) if path.exists() else None


def _json(path: Path) -> dict:
    return json.loads(path.read_text()) if path.exists() else {}


def _benchmark_table(summary: pd.DataFrame, task: ev.Task) -> str:
    metric = ev.PRIMARY_METRIC[task.kind]
    df = summary[(summary["task"] == task.name) & (summary["metric"] == metric)]
    if df.empty:
        return "_not run_\n"
    strategies = sorted(df["strategy"].unique())
    rows = []
    for model, g in df.groupby("model"):
        row = {"model": model, "features": g["features"].iloc[0]}
        for s in strategies:
            r = g[g["strategy"] == s]
            row[s] = (
                f"{_fmt(r['mean'].iloc[0])} [{_fmt(r['ci_low'].iloc[0])}, {_fmt(r['ci_high'].iloc[0])}]  (n={int(r['n_folds'].iloc[0])})"
                if len(r)
                else "–"
            )
        rows.append(row)
    out = pd.DataFrame(rows)
    key = "grouped" if "grouped" in strategies else strategies[0]
    ref = df[df["strategy"] == key].set_index("model")["mean"]
    out = out.set_index("model").loc[ref.sort_values(ascending=False).index].reset_index()
    return (
        f"Metric: **{metric}**, mean [95 % bootstrap CI over folds] (n = fold scores); columns are CV split strategies.\n\n"
        + _table(out, ["model", "features", *strategies])
    )


def build_report(results_dir: Path = cfg.RESULTS_DIR) -> str:
    from .pipeline import TASKS  # local import: pipeline imports reporting lazily

    meta = _json(results_dir / "metadata.json")
    opts = meta.get("options", {})
    d = meta.get("data", {})
    summary = _csv(cfg.DRUG_SUMMARY_FILE)
    targets = _csv(cfg.FEATURES_FILE)
    bench = _csv(results_dir / "benchmark" / "summary.csv")
    scramble = _json(results_dir / "benchmark" / "y_scrambling_summary.json")
    novelty = _json(results_dir / "models" / "novelty_metrics.json")
    clusters = _json(results_dir / "clustering" / "metrics.json")
    sim = _json(results_dir / "similarity" / "similarity_summary.json")
    cand_file = results_dir / "similarity" / "candidates.txt"
    candidates = cand_file.read_text().split() if cand_file.exists() else []
    pairs = _csv(results_dir / "combination_therapy" / "pair_scores.csv")
    screen = _json(results_dir / "interactions" / "interaction_summary.json")
    enrichment = _csv(results_dir / "pathways" / "enrichment_selective_vs_screened.csv")
    notes = _json(results_dir / "pathways" / "enrichment_notes.json")

    parts: list[str] = ["# Results\n"]
    parts.append(
        "_Auto-generated by `gbm_drug.reporting` from the tables in this directory. "
        "Do not edit by hand; see `metadata.json` for code version, environment and settings, "
        "and `docs/RESULTS.md` for interpretation._\n"
    )
    if meta:
        parts.append(
            f"Run: {meta.get('timestamp_utc', '')} · commit `{str(meta.get('git_commit', ''))[:10]}` · dirty tree: {meta.get('git_dirty')} · {meta.get('platform', '')}\n"
        )

    # 1. data
    parts.append("## 1. Data\n")
    parts.append(
        f"- GDSC release {cfg.GDSC_RELEASE}, cell lines with `TCGA_DESC == {cfg.GBM_TCGA_LABEL}`: "
        f"**{d.get('n_curves', '–')} dose-response curves**, **{d.get('n_cell_lines', '–')} cell lines**, "
        f"**{d.get('n_drugs', '–')} drugs** ({', '.join(d.get('datasets', []))}).\n"
        f"- GBM-selective drugs (one-sample t-test of GDSC z-scores vs 0, BH FDR < {cfg.SELECTIVITY_FDR}, "
        f"mean z ≤ {cfg.SELECTIVITY_Z_EFFECT}, ≥ {cfg.SELECTIVITY_MIN_CELL_LINES} lines): **{d.get('n_gbm_selective', '–')}**.\n"
        f"- Potent drugs (geometric-mean IC50 < 1 µM): **{d.get('n_potent', '–')}**.\n"
    )
    if targets is not None:
        parts.append(
            f"- Drugs with a usable small-molecule structure: **{len(targets)}** "
            f"({targets['inchikey_parent'].str.split('-').str[0].nunique()} unique molecules, "
            f"{targets['scaffold'].replace('', np.nan).nunique()} Bemis–Murcko scaffolds); "
            f"{int(targets['gbm_selective'].sum())} of them GBM-selective.\n"
        )
    if summary is not None:
        top = summary.nsmallest(15, "z_mean")[
            [
                "drug_name",
                "putative_target",
                "pathway_name",
                "n_cell_lines",
                "z_mean",
                "z_q",
                "ic50_um_geomean",
            ]
        ]
        parts.append("\nMost GBM-selective drugs (lowest mean z-score):\n\n" + _table(top, list(top.columns)))

    # 2. benchmark
    parts.append("## 2. Structure → response benchmark\n")
    if bench is None:
        parts.append("_benchmark stage not run_\n")
    else:
        parts.append(
            f"Protocol: one row per molecule; {cfg.CV_FOLDS}-fold CV grouped by InChIKey connectivity block "
            f"(`grouped`, {opts.get('cv_repeats', '?')} repeat(s)) and by Bemis–Murcko scaffold (`scaffold`, deterministic, 1 repeat); "
            f"GNN models use {opts.get('gnn_repeats', '?')} grouped repeat(s). Baseline = mean / class-prior predictor. "
            "Feature blocks: `descriptors` (13 RDKit descriptors), `morgan` (2048-bit ECFP4), `smiles` (molecular graph, GNN), "
            "`pathway` (one-hot of GDSC's target-pathway annotation), `descriptors_pathway` (both). "
            "Hyper-parameters are fixed a priori (no tuning on this data).\n"
        )
        for task in TASKS:
            parts.append(f"### {task.name} — {task.description}\n")
            parts.append(_benchmark_table(bench, task))
        if scramble:
            rows = pd.DataFrame([{"task": k, **v} for k, v in scramble.items()])
            parts.append("### Label-permutation null (y-scrambling)\n")
            parts.append(
                "Best tabular model per task under grouped CV, re-run with labels permuted across molecules. "
                "`empirical_p` = (rounds scoring ≥ real + 1) / (rounds + 1).\n\n"
                + _table(rows, ["task", "model", "metric", "real", "null_mean", "empirical_p", "n_rounds"])
            )

    # 3-4. novelty, clustering
    if novelty:
        parts.append("## 3. One-class novelty scoring (exploratory)\n")
        parts.append(
            f"One-Class SVM fitted on GBM-selective drugs, scored out-of-fold. Separation of held-out selective drugs from the rest: ROC-AUC {_fmt(novelty.get('roc_auc'))}, PR-AUC {_fmt(novelty.get('pr_auc'))} (chance PR-AUC ≈ positive rate).\n"
        )
    if clusters:
        km, db, ward, pca = (
            clusters.get("kmeans", {}),
            clusters.get("dbscan", {}),
            clusters.get("ward", {}),
            clusters.get("pca", {}),
        )
        parts.append("## 4. Descriptor-space clustering (descriptive)\n")
        parts.append(
            f"K-means k = {km.get('k', '–')} chosen by silhouette ({_fmt(km.get('silhouette'))}); Ward silhouette {_fmt(ward.get('silhouette'))}; "
            f"DBSCAN: {db.get('n_clusters', '–')} clusters, {db.get('n_noise', '–')} noise points. PCA 2-D explains {_fmt(pca.get('explained_variance_2d'))} of descriptor variance.\n"
        )

    # 5. similarity
    if sim:
        parts.append("## 5. Similarity of candidate drugs\n")
        parts.append(
            f"Candidate set: {len(candidates)} drugs (GBM-selective ∪ top {opts.get('top_n', '?')} by selectivity, capped at {opts.get('mcs_max_drugs', '?')} for MCS).\n"
        )
        rows = pd.DataFrame([{"view": k, **v} for k, v in sim.items() if k != "mantel"])
        parts.append(_table(rows, list(rows.columns)))
        if sim.get("mantel"):
            mrows = pd.DataFrame([{"pair": k, **v} for k, v in sim["mantel"].items()])
            parts.append(
                "Mantel correlation between views (Spearman r, permutation p, 999 permutations):\n\n"
                + _table(mrows, ["pair", "r", "p", "n_drugs", "n_pairs"])
            )

    # 6. combinations
    if pairs is not None:
        parts.append("## 6. Combination hypotheses (heuristic, unvalidated)\n")
        kept = pairs[pairs["excluded_reason"].isna()]
        parts.append(
            f"Weights: {cfg.COMBINATION_WEIGHTS}. Pairs with Tanimoto > {cfg.COMBINATION_MAX_TANIMOTO} excluded as near-duplicates "
            f"({int(pairs['excluded_reason'].notna().sum())} of {len(pairs)}). Scores are a ranking heuristic from single-agent data, not synergy predictions.\n\n"
            + _table(
                kept.head(15),
                [
                    "rank",
                    "drug_a",
                    "drug_b",
                    "total_score",
                    "target_diversity",
                    "pathway_complementarity",
                    "potency",
                    "structural_novelty",
                    "tanimoto",
                    "rationale",
                ],
            )
        )
        if screen:
            parts.append(
                f"Structural screen of the top {screen.get('n_pairs')} pairs: "
                + ", ".join(
                    f"{k.replace('n_', '')} = {v}"
                    for k, v in screen.items()
                    if k.startswith("n_") and k != "n_pairs"
                )
                + f". {screen.get('note', '')}\n"
            )

    # 7. pathways
    parts.append("## 7. Pathway enrichment of GBM-selective drug targets\n")
    if enrichment is None:
        parts.append(f"_not available_ ({notes.get('error', 'stage not run')})\n")
    else:
        parts.append(
            f"Query: {notes.get('n_query_genes')} target genes of {notes.get('n_selective_drugs')} GBM-selective drugs; background: {notes.get('n_background_genes')} target genes of all screened drugs "
            f"({notes.get('n_drugs_with_mapped_targets')} drugs with mapped targets, {notes.get('n_drugs_with_unmapped_tokens')} with unmapped tokens). Hypergeometric test, BH FDR within each library.\n"
        )
        sig = enrichment[enrichment["q"] < cfg.PATHWAY_FDR].sort_values("q").head(20)
        parts.append(
            f"{notes.get('n_significant', 0)} terms at FDR < {cfg.PATHWAY_FDR}"
            + (
                ":\n\n"
                + _table(sig, ["library", "term", "overlap", "set_size", "fold_enrichment", "q", "genes"])
                if len(sig)
                else ".\n"
            )
        )

    # run
    timings = meta.get("timings_seconds", {})
    if timings:
        parts.append("## Run\n")
        parts.append(
            ", ".join(f"{k} {v}s" for k, v in timings.items()) + f" — total {sum(timings.values()):.0f}s.\n"
        )
    return "\n".join(parts)


def write_results_markdown(ctx, path: Path) -> Path:
    """Build the report from disk artifacts (ctx is accepted for API compatibility)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_report(path.parent))
    return path
